blank_issues_enabled: false
contact_links:
  - name: Pocket Documentation
    url: https://github.com/frgmt0/pocket/blob/main/README.md
    about: Check the documentation before opening an issue
  - name: Discussions
    url: https://github.com/frgmt0/pocket/discussions
    about: For questions, ideas, or general discussion about Pocket 